2025-07-10 12:04:20,627 [WARNING] PyNaCl is not installed, voice will NOT be supported
2025-07-10 12:04:20,628 [INFO] logging in using static token
2025-07-10 12:04:21,410 [INFO] Shard ID None has connected to Gateway (Session ID: 62759896ac9bae48b808932eb239a53b).
2025-07-10 12:04:27,236 [INFO] ðŸ“¨ Message received â€” User: 8ruhmomentum (ID: 485308464050995245)
2025-07-10 12:04:27,236 [INFO] ðŸ“¨ Channel: general (ID: 1384535346905092127)
2025-07-10 12:04:27,236 [INFO] ðŸ’¬ Content: ask: Show me all employees
2025-07-10 12:04:27,713 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/justin/Infosys/discord_chatbot/.venv/lib/python3.12/site-packages/discord/client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "/home/justin/Infosys/discord_chatbot/discord_bot.py", line 239, in on_message
    response = agent.invoke({
               ^^^^^^^^^^^^^^
  File "/home/justin/Infosys/discord_chatbot/agent.py", line 101, in invoke
    return self.graph.invoke(state, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/Infosys/discord_chatbot/.venv/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 2719, in invoke
    for chunk in self.stream(
  File "/home/justin/Infosys/discord_chatbot/.venv/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 2436, in stream
    for _ in runner.tick(
  File "/home/justin/Infosys/discord_chatbot/agent.py", line 281, in conductor
    response = self.llm_with_tools.invoke(system_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/Infosys/discord_chatbot/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 5431, in invoke
    return self.bound.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/home/justin/Infosys/discord_chatbot/.venv/lib/python3.12/site-packages/langchain_google_genai/chat_models.py", line 1255, in invoke
    return super().invoke(input, config, stop=stop, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/Infosys/discord_chatbot/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 373, in invoke
    [self._convert_input(input)],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/Infosys/discord_chatbot/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 358, in _convert_input
    raise ValueError(msg)
ValueError: Invalid input type <class 'langchain_core.messages.human.HumanMessage'>. Must be a PromptValue, str, or list of BaseMessages.
During task with name 'conductor' and id 'a08a3320-a1a9-09ad-6fe6-e8736071f096'
